trigger:
  - main

pool:
  name: adir-agent

variables:
  resourceGroup: "MyResourceGroup"
  location: "eastus"
  templateFile: "storagesTemplate.json"
  deploymentName: "ResourceGroupDeployment"
  System.Debug: true

stages:
  - stage: DeployResourceGroup
    displayName: "Deploy Resource Group"
    jobs:
      - job: DeployResources
        displayName: "Deploy ARM Template"
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploy ARM Template"
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: "AdirConnection"
              subscriptionId: "bbe586c3-363a-4dc7-9f08-3ee4a898c1f4"
              action: "Create Or Update Resource Group"
              resourceGroupName: "$(resourceGroup)"
              location: "$(location)"
              templateLocation: "Linked artifact"
              csmFile: "$(System.DefaultWorkingDirectory)/$(templateFile)"
              deploymentMode: "Incremental"
